# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98a9446acd1e42d549a65b51068af850761b3687b103de6aa71ce05fabdb684372e17c7f967b76fe8b18fcfe6eb7fef3953d6e64b1a255b458c2281666ada94d

test:
  secret_key_base: 7d35a5c7120d829dfe4a081148e0e04198e49a3f1070682f4071e93fc3aa0836e2221240dea1b5749c789f8bb2c05721f8a5da5ad3b71088e2ce5c657fbe359d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
